### ISSUE TITLE
doesnt download properly

### ISSUE THREAD

**Issue by art5y** [pastasfuture/com.hauntedpsx.render-pipelines.psx#5]
When I try to open unity the package starts downloading then says this:
<img width="313" alt="2021-01-02 (2)" src="https://user-images.githubusercontent.com/76858451/103450406-fd05eb00-4d09-11eb-85d4-4ffa0a43232a.png">

I don't know if I've done something wrong, or if this is an easy fix since the only code I know is HTML but If anyone could help that'd be great

**Comment by art5y** [comment]
fixed it! just forgot to put a comma at the end of the line lol

**Comment by bellemish** [comment]
> fixed it! just forgot to put a comma at the end of the line lol

Could you possibly explain fursther or send a screeshot? I'm still having problems with installation.Thanks!

**Comment by art5y** [comment]
> > fixed it! just forgot to put a comma at the end of the line lol
> 
> Could you possibly explain fursther or send a screeshot? I'm still having problems with installation.Thanks!

Here's a link to the installation guide in case you didn't see it:
https://github.com/pastasfuture/com.hauntedpsx.render-pipelines.psx/wiki/Installation-Guide

and I fixed my problem by adding a comma after "com.hauntedpsx.render-pipelines.psx":"https://github.com/pastasfuture/com.hauntedpsx.render-pipelines.psx.git"**,**

I hope that was slightly clearer?
